extend-exclude = ["legacy_code"]

line-length = 88
indent-width = 4
target-version = "py312"

fix = true

[lint]
select = [
    "E",
    "F",
    "I",
    "W",
    "ISC",
    "ERA",
    "FIX",
    "TD",
    "E301",
    "E302",
    "E303",
    "E304",
    "E305",
    "E306",
]

ignore = ["W191"]

preview = true
explicit-preview-rules = true

[lint.flake8-implicit-str-concat]
allow-multiline = false

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"