from core.metrics.enums import ReduceProtocol
from core.reporting.query import Query

ES_QUERIES = (
    Query(
        title="Fitness over outer optimization iterations",
        x=("iter",),
        y=(
            (
                "by_mechanism",
                ReduceProtocol.SERIES,
                "fitness",
            ),
            (
                "by_mechanism",
                ReduceProtocol.MEAN,
                "fitness",
            ),
            ("fitness_best",),
        ),
        legend_labels=(
            "Candidates",
            "Generation mean",
            "Generation best",
        ),
        plot_modes=(
            "markers",
            "lines+markers",
            "lines+markers",
        ),
        show_group_labels=False,
        x_label="outer optimization iteration",
        y_label="objective fitness",
        error="std",
        error_path=("by_mechanism",),
    ),
    Query(
        title="Candidate fitness vs fixed quota",
        x=(
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_parameter",
            "fixed_quota",
            "value",
        ),
        y=(
            "by_mechanism",
            ReduceProtocol.SERIES,
            "fitness",
        ),
        legend_labels=("Evaluated mechanisms",),
        plot_modes=("markers",),
        show_group_labels=False,
        color=("iter",),
        color_label="Outer iteration",
        colorscale="Viridis",
        x_label="fixed quota",
        y_label="objective fitness",
    ),
    Query(
        title="Restoration subsidy vs fixed quota",
        x=(
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_parameter",
            "restoration_subsidy",
            "value",
        ),
        y=(
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_parameter",
            "fixed_quota",
            "value",
        ),
        legend_labels=("Evaluated mechanisms",),
        plot_modes=("markers",),
        show_group_labels=False,
        color=("iter",),
        color_label="Outer iteration",
        colorscale="Viridis",
        x_label="restoration subsidy",
        y_label="fixed quota",
    ),
    Query(
        title="Final train vs eval episode return",
        legend_labels=("train", "eval"),
        x=("iter",),
        y=(
            (
                "inner",
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "reward_mean",
            ),
            (
                "inner",
                "eval",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "reward_mean",
            ),
        ),
        x_label="ES generation",
        y_label="Episode return",
        error="std",
        error_path=(
            "inner",
            "eval",
            "rollout",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
    Query(
        title="Final train vs eval quota penalty",
        legend_labels=("train", "eval"),
        x=("iter",),
        y=(
            (
                "inner",
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "by_agent",
                ReduceProtocol.MEAN,
                "quota_penalty",
            ),
            (
                "inner",
                "eval",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "by_agent",
                ReduceProtocol.MEAN,
                "quota_penalty",
            ),
        ),
    ),
    Query(
        title="Final train vs eval intrinsic utility",
        legend_labels=("train", "eval"),
        x=("iter",),
        y=(
            (
                "inner",
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "by_agent",
                ReduceProtocol.MEAN,
                "intrinsic_utility",
            ),
            (
                "inner",
                "eval",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "by_agent",
                ReduceProtocol.MEAN,
                "intrinsic_utility",
            ),
        ),
    ),
    Query(
        title="Final train vs eval mean normalized fish biomass",
        legend_labels=("train", "eval"),
        x=("iter",),
        y=(
            (
                "inner",
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_mean",
            ),
            (
                "inner",
                "eval",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_mean",
            ),
        ),
    ),
    Query(
        title="Final train vs eval minimum normalized fish biomass",
        legend_labels=("train", "eval"),
        x=("iter",),
        y=(
            (
                "inner",
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_min",
            ),
            (
                "inner",
                "eval",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_min",
            ),
        ),
    ),
    Query(
        title="Final train vs eval maximum normalized fish biomass",
        legend_labels=("train", "eval"),
        x=("iter",),
        y=(
            (
                "inner",
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_max",
            ),
            (
                "inner",
                "eval",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_max",
            ),
        ),
    ),
    Query(
        title="Final train vs eval terminal normalized fish biomass",
        legend_labels=("train", "eval"),
        x=("iter",),
        y=(
            (
                "inner",
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_last",
            ),
            (
                "inner",
                "eval",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_last",
            ),
        ),
    ),
)
INNER_QUERIES = (
    Query(
        title="Episode return mean over training episodes",
        legend_labels=("train",),
        x=("iter",),
        y=(
            (
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "reward_mean",
            ),
        ),
        x_label="training episode",
        y_label="return mean",
        error="std",
        error_path=(
            "train",
            "rollout",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
    # TODO two ways over junction : either plot them in separete line or mean over
    # TODO what if you wanna avergae over specific type of agent ?
    # TODO seeding : is error bar, by_episode is mean, by_agent is mean -> for that we leave the separation int he mapping. ID should be by type strictly
    Query(
        title="Quota penalty mean over training episdoes",
        legend_labels=("train",),
        x=("iter",),
        y=(
            (
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "by_agent",
                ReduceProtocol.MEAN,
                "quota_penalty",
            ),
        ),
        x_label="training episode",
        y_label="quota penalty",
        error="std",
        error_path=(
            "train",
            "rollout",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
    Query(
        title="Intrinsic utility mean over training episdoes",
        legend_labels=("train",),
        x=("iter",),
        y=(
            (
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "by_agent",
                ReduceProtocol.MEAN,
                "intrinsic_utility",
            ),
        ),
        x_label="training episode",
        y_label="intrinsic_utility",
        error="std",
        error_path=(
            "train",
            "rollout",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
    Query(
        title="Mean normalized fish biomass over training episdoes",
        legend_labels=("train",),
        x=("iter",),
        y=(
            (
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_mean",
            ),
        ),
        x_label="training episode",
        y_label="normalized mean fish biomass",
        error="std",
        error_path=(
            "train",
            "rollout",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
    Query(
        title="Min normalized fish biomass over training episdoes",
        legend_labels=("train",),
        x=("iter",),
        y=(
            (
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_min",
            ),
        ),
        x_label="training episode",
        y_label="normalized min fish biomass",
        error="std",
        error_path=(
            "train",
            "rollout",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
    Query(
        title="Max normalized fish biomass over training episdoes",
        legend_labels=("train",),
        x=("iter",),
        y=(
            (
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_max",
            ),
        ),
        x_label="training episode",
        y_label="normalized max fish biomass",
        error="std",
        error_path=(
            "train",
            "rollout",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
    Query(
        title="Terminal rollout normalized fish biomass over training episdoes",
        legend_labels=("train",),
        x=("iter",),
        y=(
            (
                "train",
                "rollout",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_episode",
                ReduceProtocol.MEAN,
                "fish_norm_next_last",
            ),
        ),
        x_label="training episode",
        y_label="normalized terminal fish biomass",
        error="std",
        error_path=(
            "train",
            "rollout",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
    # TODO Again seeding over policy ? error bars ?
    Query(
        title="Value loss over training episdoes",
        legend_labels=("train",),
        x=("iter",),
        y=(
            (
                "train",
                "learner",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_policy",
                ReduceProtocol.SERIES,
                "value_loss",
            ),
        ),
        x_label="training episode",
        y_label="value loss",
        error="std",
        error_path=(
            "train",
            "learner",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
    Query(
        title="Total loss over training episodes",
        legend_labels=("train",),
        x=("iter",),
        y=(
            (
                "train",
                "learner",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_policy",
                ReduceProtocol.SERIES,
                "total_loss",
            ),
        ),
        x_label="training episode",
        y_label="total loss",
        error="std",
        error_path=(
            "train",
            "learner",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
    Query(
        title="policy_loss over training episodes",
        legend_labels=("train",),
        x=("iter",),
        y=(
            (
                "train",
                "learner",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_policy",
                ReduceProtocol.SERIES,
                "policy_loss",
            ),
        ),
        x_label="training episode",
        y_label="policy loss",
        error="std",
        error_path=(
            "train",
            "learner",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
    Query(
        title="Policy entropy over training episodes",
        legend_labels=("train",),
        x=("iter",),
        y=(
            (
                "train",
                "learner",
                "by_mechanism",
                ReduceProtocol.SERIES,
                "by_seed",
                ReduceProtocol.MEAN,
                "by_policy",
                ReduceProtocol.SERIES,
                "policy_entropy",
            ),
        ),
        x_label="training episode",
        y_label="policy entropy",
        error="std",
        error_path=(
            "train",
            "learner",
            "by_mechanism",
            ReduceProtocol.SERIES,
            "by_seed",
        ),
    ),
)

# TODO x and y axis labels
# TODO eval vs training from different logger instances
FISHERY_ENV_QUERIES = (
    # TODO since risk penality is null, violation singal == quota_penalty
    Query(
        title="mean quota penalty over agent",
        legend_labels=("quota penalty",),
        x=("iter",),
        y=("by_agent", ReduceProtocol.MEAN, "quota_penalty"),
    ),
    # TODO plot none when the data is not pushed to prevent experiemnt breaking
    Query(
        title="intrinsic utility mean over agent",
        legend_labels=("intrinsic utility",),
        x=("iter",),
        y=("by_agent", ReduceProtocol.MEAN, "intrinsic_utility"),
    ),
    Query(
        title="Normalized Fish biomass",
        legend_labels=("normalized fish biomass",),
        x=("iter",),
        y=("fish_norm",),
    ),
)
